# Generated by Django 3.2.9 on 2021-12-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/profile_pics/userimage.png', upload_to='profile_pics/'),
        ),
    ]
