# Generated by Django 3.2.8 on 2021-10-28 16:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
