# Generated by Django 3.2.8 on 2021-11-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='device',
        ),
    ]
