# Generated by Django 3.2.8 on 2021-11-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_customer_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
    ]
