# Generated by Django 3.2.8 on 2021-11-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_cart_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
