# Generated by Django 3.2.9 on 2021-11-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20211116_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
