# Generated by Django 3.2.9 on 2021-11-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_customer_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
