# Generated by Django 3.2.9 on 2021-11-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_type',
        ),
    ]
