# Generated by Django 3.2.9 on 2021-11-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('SELF', 'self'), ('DELIVERY', 'delivery')], default='DELIVERY', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new', 'new'), ('in-progress', 'in-progress'), ('is-ready', 'is-ready'), ('completed', 'completed')], default='new', max_length=50),
        ),
    ]
