# Generated by Django 3.2.9 on 2021-11-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_users_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wishlist',
        ),
    ]
