# Generated by Django 3.2.9 on 2021-11-18 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0020_remove_customer_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, related_name='users_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
