# Generated by Django 3.2.9 on 2021-11-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_status',
            field=models.CharField(choices=[('calendar', 'calendar'), ('clapperboard', 'clapperboard'), ('drive', 'drive')], default='calendar', max_length=20),
        ),
    ]
