# Generated by Django 3.2.8 on 2021-10-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('message', models.TextField()),
                ('attachement', models.FileField(blank=True, null=True, upload_to='')),
                ('send_it', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscribers', models.ManyToManyField(to='home.SubscribedUser')),
            ],
        ),
    ]
