# Generated by Django 3.2.9 on 2021-12-01 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211028_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmessage',
            name='id',
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='msgid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='subject',
            field=models.CharField(default='Thanking you', max_length=100),
        ),
    ]
