# Generated by Django 3.2.9 on 2021-12-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211201_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailMessage',
        ),
    ]
