# Generated by Django 3.2.9 on 2021-12-01 18:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_mailmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(default='Thanking you', max_length=100)),
                ('message', models.TextField()),
                ('attachement', models.FileField(blank=True, null=True, upload_to='')),
                ('send_it', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscribers', models.ManyToManyField(to='home.SubscribedUser')),
            ],
        ),
    ]
