# Generated by Django 3.2.9 on 2021-12-01 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_mailmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmessage',
            name='id',
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='msgid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
