# Generated by Django 3.2.9 on 2021-12-01 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211201_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmessage',
            name='msgid',
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
