# Generated by Django 3.2.9 on 2021-12-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_mailmessage_attachement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmessage',
            name='subscribers',
        ),
    ]
