# Generated by Django 3.2.9 on 2021-12-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_mailmessage_subscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailMessage',
        ),
    ]
